import Head from 'next/head';
import Image from 'next/image';
import slider from './slider';

import styles from '../styles/Home.module.css';
import Hero from "../components/Hero/Hero";
import Navbar from "../components/UI/Navbar";
import Description from "../components/Description/Description";
import Footer from "../components/UI/Footer";
import Info from "../components/Info/Info";
import Galerry from "../components/Galery/Galerry";


export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Navbar/>
			<Hero/>
			<Description />
			<Info />
			<Galerry />
			<Footer />
		</div>
	);
}
